name: G++ C++ Build and Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository code
      uses: actions/checkout@v4

    - name: Compile Windows Resources (windres)
      run: |
        windres resource.rc -o resource.o

    - name: Compile and Link C++ App (g++)
      run: |
        & g++ -O3 -finput-charset=UTF-8 -fexec-charset=UTF-8 main.cpp resource.o -o Piano.exe -lgdi32 -luser32 -lgdiplus -lwinmm -static -mwindows "-Wl,--file-alignment=0x1000" "-Wl,--section-alignment=0x1000"

    - name: Strip Debug Symbols (strip)
      run: |
        strip Piano.exe

    - name: Create Official GitHub Release and Upload EXE
      uses: softprops/action-gh-release@v2
      with:
        files: Piano.exe
        name: Release ${{ github.ref_name }}
        tag_name: ${{ github.ref }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
