name: MSVC C++ Build and Release

on:
  push:
    tags:
      - "v*" # Скрипт будет срабатывать ТОЛЬКО когда вы отправляете тег (например, v2.8.0)

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write # Даем GitHub право создавать релизы и загружать файлы

    steps:
    - name: Checkout repository code
      uses: actions/checkout@v4

    - name: Enable MSVC Command Prompt Environment
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64

    - name: Compile Windows Resources (rc.exe)
      run: |
        rc resource.rc

    - name: Compile and Link C++ App (cl.exe)
      run: |
        cl /O1 /analyze- /MT main.cpp resource.res /link /SUBSYSTEM:WINDOWS user32.lib gdi32.lib gdiplus.lib /OUT:IQ.exe

    - name: Create Official GitHub Release and Upload EXE
      uses: softprops/action-gh-release@v2
      with:
        files: IQ.exe
        name: Release ${{ github.ref_name }}
        tag_name: ${{ github.ref }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}